In [10]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]


In [12]:
#Define Vocab size
voc_size=10000

In [13]:
one_hot_rep= [one_hot(words,voc_size)for words in sent]
one_hot_rep

[[7418, 9174, 4512, 5227],
 [7418, 9174, 4512, 7859],
 [7418, 1251, 4512, 8809],
 [2181, 1179, 2492, 91, 8169],
 [2181, 1179, 2492, 91, 619],
 [1901, 7418, 4938, 4512, 8258],
 [1339, 4797, 8201, 91]]

In [14]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7418 9174 4512 5227]
 [   0    0    0    0 7418 9174 4512 7859]
 [   0    0    0    0 7418 1251 4512 8809]
 [   0    0    0 2181 1179 2492   91 8169]
 [   0    0    0 2181 1179 2492   91  619]
 [   0    0    0 1901 7418 4938 4512 8258]
 [   0    0    0    0 1339 4797 8201   91]]
