In [10]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]


In [12]:
#Define Vocab size
voc_size=10000

In [13]:
one_hot_rep= [one_hot(words,voc_size)for words in sent]
one_hot_rep

[[7418, 9174, 4512, 5227],
 [7418, 9174, 4512, 7859],
 [7418, 1251, 4512, 8809],
 [2181, 1179, 2492, 91, 8169],
 [2181, 1179, 2492, 91, 619],
 [1901, 7418, 4938, 4512, 8258],
 [1339, 4797, 8201, 91]]

In [14]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7418 9174 4512 5227]
 [   0    0    0    0 7418 9174 4512 7859]
 [   0    0    0    0 7418 1251 4512 8809]
 [   0    0    0 2181 1179 2492   91 8169]
 [   0    0    0 2181 1179 2492   91  619]
 [   0    0    0 1901 7418 4938 4512 8258]
 [   0    0    0    0 1339 4797 8201   91]]


In [19]:
#Feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 314ms/step


array([[[-0.03310984,  0.03942139, -0.00406522, -0.01339601,
          0.0037362 ,  0.02680714, -0.03818781,  0.01428512,
         -0.02907901, -0.04575482],
        [-0.03310984,  0.03942139, -0.00406522, -0.01339601,
          0.0037362 ,  0.02680714, -0.03818781,  0.01428512,
         -0.02907901, -0.04575482],
        [-0.03310984,  0.03942139, -0.00406522, -0.01339601,
          0.0037362 ,  0.02680714, -0.03818781,  0.01428512,
         -0.02907901, -0.04575482],
        [-0.03310984,  0.03942139, -0.00406522, -0.01339601,
          0.0037362 ,  0.02680714, -0.03818781,  0.01428512,
         -0.02907901, -0.04575482],
        [-0.0402379 ,  0.02480829, -0.02828866, -0.01259102,
          0.02940119,  0.03830561,  0.01947626, -0.00159402,
         -0.02582604,  0.01138507],
        [-0.03162553,  0.00380776, -0.03607936,  0.02737752,
          0.0419342 , -0.01705122,  0.01065836,  0.03280667,
         -0.0003766 , -0.03769486],
        [ 0.01833424,  0.00149246, -0.00231689,  0.0